### ISSUE TITLE
Button styles remain after uninstall

### ISSUE THREAD

**Issue by spbuda** [kamyker/UnityDarkenThemer#1]
I installed this through git, decided I didn't want to spend time to mess with it right now and uninstalled it following your instructions in the readme, That is- I Removed it via package manager, shut down unity and deleted the Styles library file. Then relaunched. While it mostly worked, it seems the button styles are persisting somewhat. Any thoughts on how to get those back to normal?

![image](https://user-images.githubusercontent.com/9916954/84678813-b24b8f80-aeed-11ea-94f3-c28e102bffef.png)

Edit: for reference, I am using Unity 2019.4.0 LTS

**Comment by kamyker** [comment]
Forgot about that - also remove "Assets\Editor Default Resources\Icons" folder, adding it to readme

**Comment by pixelbreaker** [comment]
I uninstalled and it doesn't remove the darkness, so unity is totally unusable now.

**Comment by kamyker** [comment]
Have you `Remove "Library\Style.catalog" file as that's where Unity caches style sheets.` ?
