### ISSUE TITLE
[2019.4] Errors of missing textures after clicking Tools > Darken > Quick Fix

### ISSUE THREAD

**Issue by hlo-world** [kamyker/UnityDarkenThemer#2]
Windows 10
Unity 2019.4

To reproduce:
1. Create New Project
2. Install UnityDarkenThemer
3. Tools > Darken > Create Textures
4. Create a Script
5. Click Script, Inspector windows opens with script
6. Tools > Darken > Quick Fix
7. Errors appear:

![errors](https://user-images.githubusercontent.com/9633055/85234801-ffdc6680-b3dd-11ea-90cc-d81133532bc0.png)

**Comment by kamyker** [comment]
These errors can be ignored as some textures are omitted during "Create Textures" step on purpose.

Maybe will hide them in future.

**Comment by kamyker** [comment]
fixed
